### ISSUE TITLE
最新版运行后，在窗口中输入6，回车后报错，希望帮忙看下怎么解决，谢谢

### ISSUE THREAD

**Issue by 469312306** [Dawnnnnnn/bilibili-live-tools#116]
Task exception was never retrieved
future: <Task finished coro=<check_taskinfo() done, defined at C:\Users\yy\Downloads\bilibili-live-tools\utils.py:154> exception=ContentTypeError("0, message='Attempt to decode JSON with unexpected mimetype: text/json; charset=utf-8'",)>
Traceback (most recent call last):
  File "C:\Users\yy\Downloads\bilibili-live-tools\utils.py", line 156, in check_taskinfo
    json_response = await response.json()
  File "C:\Users\yy\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiohttp\client_reqrep.py", line 927, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/json; charset=utf-8'

**Comment by yjqiang** [comment]
aiohttp 对json的解析要求很严格，b站没有写json的header
