### ISSUE TITLE
报错#无法领取登船福利

### ISSUE THREAD

**Issue by ShineZcx** [Dawnnnnnn/bilibili-live-tools#123]
隐去盘符名
Traceback (most recent call last):
  File "$\bilibili-live-tools-master\OnlineHeart.py", line 87, in run
    await self.guard_lottery()
  File "$\bilibili-live-tools-master\OnlineHeart.py", line 29, in guard_lottery
    json_response = response.json()
  File "$\Anaconda3\lib\site-packages\requests\models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "$\Anaconda3\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "$\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "$\Anaconda3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Dawnnnnnn** [comment]
服务器短暂性爆炸，已恢复
