### ISSUE TITLE
在 Travis CI 上运行报错

### ISSUE THREAD

**Issue by VergeDX** [Dawnnnnnn/bilibili-live-tools#130]
`````python
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from OnlineHeart import OnlineHeart
  File "/home/travis/build/VergeDX/bilibili-live-tools/OnlineHeart.py", line 16
    async def apppost_heartbeat(self):
            ^
SyntaxError: invalid syntax
``````
这是 run.sh 脚本：
`````shell
python3 run.py &
sleep 12
ps -ef | grep python3 | grep -v grep | awk '{print $2}' | xargs kill -9
echo KILLED
exit
`````
小白求教 QAQ

**Comment by Dawnnnnnn** [comment]
这个报错基本上是因为用了python2

你手动执行一下python3 run.py试试

**Comment by VergeDX** [comment]
已经解决，配置文件是这样的：
`````yml
language: python
python:
  - "3.6"
sudo: enabled
install:
  - pip install -r requirements.txt
script:
  - python3.6 run.py
`````
感谢！

**Comment by VergeDX** [comment]
~~目前的配置，需要自取~~
`````yml
language: python
python:
  - "3.6"
sudo: enabled
install:
  - pip install -r requirements.txt
  - sudo apt update
  - sudo apt install screen
script:
  - screen -L -dm python3 run.py
  - sleep 27
  - cat screenlog.0
`````
