### ISSUE TITLE
疯狂报错 Orz

### ISSUE THREAD

**Issue by kaniwow** [Dawnnnnnn/bilibili-live-tools#133]
start OK!
Task exception was never retrieved
future: <Task finished coro=<login.login_new() done, defined at /root/bili1/login.py:83> exception=ConnectionError(MaxRetryError("HTTPConnectionPool(host='47.95.255.188', port=5000): Max retries exceeded with url: /code (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fedc0274e10>: Failed to establish a new connection: [Errno 111] Connection refused',))",),)>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 91, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 81, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 162, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 146, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x7fedc0274e10>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 273, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='47.95.255.188', port=5000): Max retries exceeded with url: /code (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fedc0274e10>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/bili1/login.py", line 88, in login_new
    return self.login()
  File "/root/bili1/login.py", line 59, in login
    response = self.login_with_captcha(username, password)
  File "/root/bili1/login.py", line 32, in login_with_captcha
    captcha = bilibili().cnn_captcha(tmp1)
  File "/root/bili1/bilibili.py", line 62, in cnn_captcha
    ressponse = requests.post(url, data=data)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='47.95.255.188', port=5000): Max retries exceeded with url: /code (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fedc0274e10>: Failed to establish a new connection: [Errno 111] Connection refused',))
[2018-10-18 21:38:12] [Info]         检查宝箱状态              
[2018-10-18 21:38:13] [Info]         心跳                  
[2018-10-18 21:38:13] [Info]         开始执行每日任务            
[2018-10-18 21:38:13] [Info]         连接 5560806 [手游分区]弹幕服务器成功
[2018-10-18 21:38:13] [Info]         连接 8582348 [绘画分区]弹幕服务器成功
[2018-10-18 21:38:13] [Info]         连接 5085 [游戏分区]弹幕服务器成功
[2018-10-18 21:38:13] [Info]         连接 63129 [娱乐分区]弹幕服务器成功
[2018-10-18 21:38:13] [Error]        cookie过期,将重新登录      
[2018-10-18 21:38:13] [Info]         签到状态:请先登录

**Comment by Dawnnnnnn** [comment]
验证码服务器挂掉了，你可以换个ip登录。。。

**Comment by Dawnnnnnn** [comment]
重启了下服务器，重试下吧
