### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by kobayashimu** [Dawnnnnnn/bilibili-live-tools#148]
双击打开run.py会有一过性闪退是因为？

**Comment by Dawnnnnnn** [comment]
不要双击 进cmd  python run.py才能看到报错

**Comment by kobayashimu** [comment]
File "<stdin>", line 1
    F:\bilibili-live-tools-master\run.py
                                       ^
SyntaxError: unexpected character after line continuation character

**Comment by kobayashimu** [comment]
顺便打开main.py之后是这样
start OK!
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from OnlineHeart import OnlineHeart
  File "F:\bilibili-live-tools-master\OnlineHeart.py", line 1, in <module>
    from bilibili import bilibili
  File "F:\bilibili-live-tools-master\bilibili.py", line 12, in <module>
    from printer import Printer
  File "F:\bilibili-live-tools-master\printer.py", line 1, in <module>
    from termcolor import *
ModuleNotFoundError: No module named 'termcolor'

**Comment by Dawnnnnnn** [comment]
https://blog.csdn.net/qq_38339056/article/details/80953277

**Comment by Dawnnnnnn** [comment]
装依赖库啊，重新装一遍requirements

**Comment by kobayashimu** [comment]
好用了！之前的termcolor库莫名其妙没了
