### ISSUE TITLE
这算是，被关小黑屋了？

### ISSUE THREAD

**Issue by kaniwow** [Dawnnnnnn/bilibili-live-tools#150]
> Task exception was never retrieved
future: <Task finished coro=<handle_1_TV_raffle() done, defined at /root/bili6/bilibiliCilent.py:13> exception=ContentTypeError("0, message='Attempt to decode JSON with unexpected mimetype: text/html'",)>
Traceback (most recent call last):
  File "/root/bili6/bilibiliCilent.py", line 17, in handle_1_TV_raffle
    json_response2 = await response2.json()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client_reqrep.py", line 938, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html'
Traceback (most recent call last):
  File "/root/bili6/OnlineHeart.py", line 87, in run
    await self.guard_lottery()
  File "/root/bili6/OnlineHeart.py", line 35, in guard_lottery
    json_response2 = await response2.json()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client_reqrep.py", line 938, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html'

上一次提交的issues小黑屋消息只有一个类的函数会出提示，这次的心跳类也出提示让我有点方张

**Comment by englishyj** [comment]
是的，领取上舰亲密度太频繁。

进小黑屋也无所谓，照样能挂机，只是不能领取各种礼物了。

**Comment by Dawnnnnnn** [comment]
是啊，应该已经不会出这个报错了
