### ISSUE TITLE
格式化

### ISSUE THREAD

**Issue by yjqiang** [Dawnnnnnn/bilibili-live-tools#17]
”pc端”以及”app端”建议改成”网页端”和”移动端”
参与活动抽奖显示的”加入成功”和参与小电视的”ok”建议统一改为”已加入，待开奖”

**Comment by Dawnnnnnn** [comment]
加入成功和ok都是服务器端给的回显，我直接拿来用了，可以加个if让它输出成想要的文字。后天改后天改(flag)，该睡觉了，九点还要打强网杯，晚安。

**Comment by yjqiang** [comment]
这个issue开着吧，可能后续还有类似的，有时间我看看改改(flag） 睡觉

**Comment by yjqiang** [comment]
![d11843ff-2874-4671-bc0e-108b1915db62](https://user-images.githubusercontent.com/8900942/37892840-cc4a3376-310b-11e8-88f0-4fa8e9d3cbba.png)

参考

**Comment by Dawnnnnnn** [comment]
这个图告诉我，该做风纪委员相关东西了23333

**Comment by yjqiang** [comment]
先做直播相关，主站的话就开个新的项目吧，不然太杂乱了

**Comment by emmmmmmmmmmmmmmmmm** [comment]
Traceback (most recent call last):
  File "G:\bilibili-master\OnlineHeart.py", line 1, in <module>
    from bilibili import bilibili
ModuleNotFoundError: No module named 'bilibili'
这个错误是什么意思啊？昨天晚上还可以用

**Comment by Dawnnnnnn** [comment]
你当前目录下有bilibili.py这个文件吗

**Comment by emmmmmmmmmmmmmmmmm** [comment]
Traceback (most recent call last):
  File "C:\Users\Dee丶\Desktop\bilibili-live-tools-master\connect.py", line 2, in <module>
    from bilibiliCilent import bilibiliClient
  File "C:\Users\Dee丶\Desktop\bilibili-live-tools-master\bilibiliCilent.py", line 11, in <module>
    import console
ModuleNotFoundError: No module named 'console'
我重新下了，打开还是这样

**Comment by Dawnnnnnn** [comment]
pip install console

**Comment by emmmmmmmmmmmmmmmmm** [comment]
Traceback (most recent call last):
  File "C:\Users\Dee丶\Desktop\bilibili-live-tools-master\connect.py", line 2, in <module>
    from bilibiliCilent import bilibiliClient
  File "C:\Users\Dee丶\Desktop\bilibili-live-tools-master\bilibiliCilent.py", line 12, in <module>
    from printf import printf
  File "C:\Users\Dee丶\Desktop\bilibili-live-tools-master\printf.py", line 1, in <module>
    import webcolors
ModuleNotFoundError: No module named 'webcolors'
安装pip install console后变成这样

**Comment by Dawnnnnnn** [comment]
pip install webcolors

**Comment by emmmmmmmmmmmmmmmmm** [comment]
Traceback (most recent call last):
  File "C:\Users\Dee丶\Desktop\bilibili-live-tools-master\login.py", line 43, in success
    access_key = response.json()['data']['token_info']['access_token']
KeyError: 'data'

**Comment by emmmmmmmmmmmmmmmmm** [comment]
手机登陆，昨晚还可以用- 。-

**Comment by yjqiang** [comment]
应该是被盗号了

**Comment by yjqiang** [comment]
请新开一个issue讨论此问题，因为不相干

**Comment by Dawnnnnnn** [comment]
手机登录的话，我觉得你是密码错了。如果你觉得肯定没错，那么你就在login.py
![image](https://user-images.githubusercontent.com/24506421/37965320-4542e6ec-31f7-11e8-9a10-886ca14c650b.png)这句下面，加一个print(response.json())
