### ISSUE TITLE
提示账号或者密码错误，无法正常登陆

### ISSUE THREAD

**Issue by SANSHUISHUI** [Dawnnnnnn/bilibili-live-tools#182]
输完账号和密码之后没反应了怎么办
第一次的时候说我账户或者密码错误 但是核对几遍都没问题
然后心跳那里也出错了
后面我重新开过登陆 就没反应了

**Comment by yawwwwwn** [comment]
贴log文件中异常的内容，或者至少放下运行截图。
重开也不行就重新解压，重来。
登录的问题很复杂的话先保证不需要验证。方法是换ip什么的。

**Comment by Dawnnnnnn** [comment]
密码里面是否有特殊字符，如果有，请把特殊字符打出来。没有的话，那就不可能是代码问题了，自己重新下载解压

**Comment by SANSHUISHUI** [comment]
请问能麻烦帮看一下吗
我重新下了好几次了， 而且基本上我每次打完账户与密码就没有反应,一两次成功的话就会像下面那样
账户我试过手机号和UID都不行 密码也没有错 我试过登出b站重新登陆，核对了账号和密码 都没有错


[2019-02-25 06:00:31] [Error]   登录失败,错误信息为:账号或者密码错误

[2019-02-25 06:00:31] [Info]    心跳

[2019-02-25 06:00:31] [Info]    检查宝箱状态

[2019-02-25 06:00:31] [Info]    开始执行每日任务

[2019-02-25 06:00:32] [Error]   cookie过期,将重新登录

[2019-02-25 06:00:34] [Error]   登录失败,错误信息为:账号或者密码错误

[2019-02-25 06:00:35] [Info]    签到状态:请先登录

[2019-02-25 06:00:39] [Info]    [1娱乐分区] 连接 203396 弹幕服务器成功

[2019-02-25 06:00:39] [Info]    [2网游分区] 连接 6082986 弹幕服务器成功

[2019-02-25 06:00:39] [Info]    [3手游分区] 连接 1286378 弹幕服务器成功

[2019-02-25 06:00:39] [Info]    [4绘画分区] 连接 940579 弹幕服务器成功

[2019-02-25 06:00:39] [Info]    [5电台分区] 连接 8242632 弹幕服务器成功

Traceback (most recent call last):

  File "Tasks.py", line 131, in run

  File "Tasks.py", line 23, in Daily_bag

TypeError: list indices must be integers or slices, not str

[2019-02-25 06:00:45] [Info]    开始执行每日任务

[2019-02-25 06:00:46] [Info]    签到状态:请先登录

Traceback (most recent call last):

  File "OnlineHeart.py", line 120, in run

  File "OnlineHeart.py", line 43, in guard_lottery

KeyError: 0

[2019-02-25 06:00:46] [Info]    心跳

[2019-02-25 06:00:47] [Error]   cookie过期,将重新登录

[2019-02-25 06:00:49] [Error]   登录失败,错误信息为:账号或者密码错误

Traceback (most recent call last):

  File "Tasks.py", line 131, in run

  File "Tasks.py", line 23, in Daily_bag

TypeError: list indices must be integers or slices, not str

[2019-02-25 06:00:56] [Info]    开始执行每日任务

[2019-02-25 06:00:57] [Info]    签到状态:请先登录

Traceback (most recent call last):

  File "OnlineHeart.py", line 120, in run

  File "OnlineHeart.py", line 43, in guard_lottery

KeyError: 0

[2019-02-25 06:01:00] [Info]    心跳

[2019-02-25 06:01:00] [Error]   cookie过期,将重新登录

[2019-02-25 06:01:02] [Error]   登录失败,错误信息为:账号或者密码错误

Traceback (most recent call last):

  File "Tasks.py", line 131, in run

  File "Tasks.py", line 23, in Daily_bag

TypeError: list indices must be integers or slices, not str

[2019-02-25 06:01:07] [Info]    开始执行每日任务

[2019-02-25 06:01:07] [Info]    签到状态:请先登录

Traceback (most recent call last):

  File "OnlineHeart.py", line 120, in run

  File "OnlineHeart.py", line 43, in guard_lottery

KeyError: 0

[2019-02-25 06:01:13] [Info]    心跳

[2019-02-25 06:01:14] [Error]   cookie过期,将重新登录

[2019-02-25 06:01:16] [Error]   登录失败,错误信息为:账号或者密码错误

Traceback (most recent call last):

  File "Tasks.py", line 131, in run

  File "Tasks.py", line 23, in Daily_bag

TypeError: list indices must be integers or slices, not str

[2019-02-25 06:01:18] [Info]    开始执行每日任务

[2019-02-25 06:01:18] [Info]    签到状态:请先登录

Traceback (most recent call last):

  File "OnlineHeart.py", line 120, in run

  File "OnlineHeart.py", line 43, in guard_lottery

KeyError: 0

[2019-02-25 06:01:28] [Info]    心跳

Traceback (most recent call last):

  File "Tasks.py", line 131, in run

  File "Tasks.py", line 23, in Daily_bag

TypeError: list indices must be integers or slices, not str

[2019-02-25 06:01:28] [Info]    开始执行每日任务

[2019-02-25 06:01:28] [Error]   cookie过期,将重新登录

[2019-02-25 06:01:31] [Error]   登录失败,错误信息为:账号或者密码错误

[2019-02-25 06:01:31] [Info]    签到状态:请先登录

Traceback (most recent call last):

  File "OnlineHeart.py", line 120, in run

  File "OnlineHeart.py", line 43, in guard_lottery

KeyError: 0

[2019-02-25 06:01:42] [Info]    心跳

Traceback (most recent call last):

  File "Tasks.py", line 131, in run

  File "Tasks.py", line 23, in Daily_bag

TypeError: list indices must be integers or slices, not str

[2019-02-25 06:01:42] [Info]    开始执行每日任务

[2019-02-25 06:01:42] [Error]   cookie过期,将重新登录








在 2019-02-23 23:38:41，"Dawnspace" <notifications@github.com> 写道：


密码里面是否有特殊字符，如果有，请把特殊字符打出来。没有的话，那就不可能是代码问题了，自己重新下载解压

**Comment by yjqiang** [comment]
> 请问能麻烦帮看一下吗 我重新下了好几次了， 而且基本上我每次打完账户与密码就没有反应,一两次成功的话就会像下面那样 账户我试过手机号和UID都不行 密码也没有错 我试过登出b站重新登陆，核对了账号和密码 都没有错

你密码或用户名里面含有`\`或者其他可能的特殊符号么。

**Comment by yawwwwwn** [comment]
整个的错误就是“账号或者密码错误”，导致后面的功能都因未登录而无法执行。你把账号密码里显然没问题的字符比如a-z0-9随意替换，剩下的发出来看看吧。

**Comment by yjqiang** [comment]
> 整个的错误就是“账号或者密码错误”，导致后面的功能都因未登录而无法执行。你把账号密码里显然没问题的字符比如a-z0-9随意替换，剩下的发出来看看吧。

b站会允许`\`这种东西么。。。应该不会吧

**Comment by SANSHUISHUI** [comment]
不好意思 我没注意到没有粘贴成功
下面是我早上开的软件，然后一直没有显示出任何东西。晚上再打开电脑才出现了下面这些
我的密码只包含了两个字母和1个数字，其他什么都没有
Task exception was never retrieved
future: <Task finished coro=<login.login_new() done, defined at login.py:83> exception=ConnectionError(ProtocolError('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)),)>
Traceback (most recent call last):
File "site-packages\urllib3\connectionpool.py", line 601, in urlopen
File "site-packages\urllib3\connectionpool.py", line 387, in _make_request
File "<string>", line 2, in raise_from
File "site-packages\urllib3\connectionpool.py", line 383, in _make_request
File "http\client.py", line 1331, in getresponse
File "http\client.py", line 297, in begin
File "http\client.py", line 258, in _read_status
File "socket.py", line 586, in readinto
ConnectionAbortedError: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "site-packages\requests\adapters.py", line 440, in send
File "site-packages\urllib3\connectionpool.py", line 639, in urlopen
File "site-packages\urllib3\util\retry.py", line 357, in increment
File "site-packages\urllib3\packages\six.py", line 685, in reraise
File "site-packages\urllib3\connectionpool.py", line 601, in urlopen
File "site-packages\urllib3\connectionpool.py", line 387, in _make_request
File "<string>", line 2, in raise_from
File "site-packages\urllib3\connectionpool.py", line 383, in _make_request
File "http\client.py", line 1331, in getresponse
File "http\client.py", line 297, in begin
File "http\client.py", line 258, in _read_status
File "socket.py", line 586, in readinto
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建 立的连接。', None, 10053, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "login.py", line 88, in login_new
File "login.py", line 59, in login
File "login.py", line 32, in login_with_captcha
File "bilibili.py", line 62, in cnn_captcha
File "site-packages\requests\api.py", line 112, in post
File "site-packages\requests\api.py", line 58, in request
File "site-packages\requests\sessions.py", line 508, in request
File "site-packages\requests\sessions.py", line 618, in send
File "site-packages\requests\adapters.py", line 490, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None))
[2019-02-25 13:50:58] [Info] 检查宝箱状态
[2019-02-25 13:50:58] [Info] 心跳
[2019-02-25 13:50:59] [Info] 开始执行每日任务
[2019-02-25 17:08:37] [Error] cookie过期,将重新登录
[2019-02-25 17:08:39] [Error] 登录失败,错误信息为:账号或者密码错误
[2019-02-25 17:08:39] [Info] 签到状态:请先登录
[2019-02-25 17:08:42] [Info] [4绘画分区] 连接 13989240 弹幕服务器成功
[2019-02-25 17:08:42] [Info] [5电台分区] 连接 156636 弹幕服务器成功
[2019-02-25 17:08:43] [Info] [1娱乐分区] 连接 8102705 弹幕服务器成功
[2019-02-25 17:08:43] [Info] [3手游分区] 连接 4257198 弹幕服务器成功
[2019-02-25 17:08:43] [Info] [2网游分区] 连接 12265 弹幕服务器成功
Traceback (most recent call last):
File "Tasks.py", line 131, in run
File "Tasks.py", line 23, in Daily_bag
TypeError: list indices must be integers or slices, not str
[2019-02-25 17:08:49] [Info] 开始执行每日任务
[2019-02-25 17:08:50] [Info] 签到状态:请先登录
Traceback (most recent call last):
File "OnlineHeart.py", line 120, in run
File "OnlineHeart.py", line 43, in guard_lottery
KeyError: 0
[2019-02-25 17:08:50] [Info] 心跳
[2019-02-25 17:08:54] [Error] cookie过期,将重新登录
[2019-02-25 17:08:56] [Error] 登录失败,错误信息为:账号或者密码错误
[2019-02-25 17:09:00] [Lottery] 检测到房间 9600277 的广播抽奖 @[1娱乐分区]8102705
Traceback (most recent call last):
File "Tasks.py", line 131, in run
File "Tasks.py", line 23, in Daily_bag
TypeError: list indices must be integers or slices, not str
[2019-02-25 17:09:00] [Info] 开始执行每日任务
[2019-02-25 17:09:00] [Info] 签到状态:请先登录
[2019-02-25 17:09:03] [Lottery] 参与了房间 9600277 的广播抽奖
[2019-02-25 17:09:03] [Lottery] 房间 9600277 广播道具抽奖状态: 请先登录哦
{'code': -401, 'msg': '请先登录哦', 'message': '请先登录哦', 'data': [], 'need_login': 1}
Traceback (most recent call last):
File "OnlineHeart.py", line 120, in run
File "OnlineHeart.py", line 43, in guard_lottery
KeyError: 0
[2019-02-25 17:09:07] [Info] 心跳
[2019-02-25 17:09:07] [Error] cookie过期,将重新登录
[2019-02-25 17:09:09] [Error] 登录失败,错误信息为:账号或者密码错误
Traceback (most recent call last):
File "Tasks.py", line 131, in run
File "Tasks.py", line 23, in Daily_bag
TypeError: list indices must be integers or slices, not str
[2019-02-25 17:37:10] [Info] 开始执行每日任务
[2019-02-25 17:37:10] [Error] 主动关闭或者远端主动发来FIN @[4绘画分区]13989240
[2019-02-25 17:37:10] [Error] 主动关闭或者远端主动发来FIN @[3手游分区]4257198
[2019-02-25 17:37:11] [Error] 主动关闭或者远端主动发来FIN @[5电台分区]156636
[2019-02-25 17:37:11] [Error] 主动关闭或者远端主动发来FIN @[1娱乐分区]8102705
[2019-02-25 17:37:11] [Error] 主动关闭或者远端主动发来FIN @[2网游分区]12265
Traceback (most recent call last):
File "OnlineHeart.py", line 120, in run
File "OnlineHeart.py", line 43, in guard_lottery
KeyError: 0
[2019-02-25 17:37:18] [Info] 心跳
[2019-02-25 17:37:20] [Info] [1娱乐分区] 房间 8102705 任务出现异常
[2019-02-25 17:37:23] [Error] cookie过期,将重新登录
[2019-02-25 17:37:25] [Error] 登录失败,错误信息为:账号或者密码错误
[2019-02-25 17:37:26] [Info] [1娱乐分区] 房间 8102705 直播状态正常
[2019-02-25 17:37:26] [Info] [2网游分区] 房间 12265 任务出现异常
Traceback (most recent call last):
File "connect.py", line 51, in create
File "connect.py", line 84, in check_area
KeyError: '2网游'
[2019-02-25 17:37:27] [Info] 签到状态:请先登录
[2019-02-25 17:37:28] [Info] [1娱乐分区] 连接 8102705 弹幕服务器成功
[2019-02-25 17:37:37] [Info] [2网游分区] 房间 12265 任务出现异常
Traceback (most recent call last):
File "connect.py", line 51, in create
File "connect.py", line 84, in check_area
KeyError: '2网游'
Traceback (most recent call last):
File "Tasks.py", line 131, in run
File "Tasks.py", line 23, in Daily_bag
TypeError: list indices must be integers or slices, not str
[2019-02-25 17:37:37] [Info] 开始执行每日任务
[2019-02-25 17:37:38] [Info] 签到状态:请先登录
Traceback (most recent call last):
File "OnlineHeart.py", line 120, in run
File "OnlineHeart.py", line 43, in guard_lottery
KeyError: 0
[2019-02-25 17:37:38] [Info] 心跳
[2019-02-25 17:37:38] [Error] cookie过期,将重新登录
[2019-02-25 17:37:40] [Error] 登录失败,错误信息为:账号或者密码错误
[2019-02-25 17:37:47] [Info] [2网游分区] 房间 12265 任务出现异常
Traceback (most recent call last):
File "connect.py", line 51, in create
File "connect.py", line 84, in check_area
KeyError: '2网游'
Traceback (most recent call last):
File "Tasks.py", line 131, in run
File "Tasks.py", line 23, in Daily_bag
TypeError: list indices must be integers or slices, not str
[2019-02-25 17:37:48] [Info] 开始执行每日任务
[2019-02-25 17:37:49] [Info] 签到状态:请先登录
Traceback (most recent call last):
File "OnlineHeart.py", line 120, in run
File "OnlineHeart.py", line 43, in guard_lottery
KeyError: 0
[2019-02-25 17:37:52] [Info] 心跳
[2019-02-25 17:37:52] [Error] cookie过期,将重新登录
[2019-02-25 17:37:54] [Error] 登录失败,错误信息为:账号或者密码错误
[2019-02-25 17:37:57] [Info] [2网游分区] 房间 12265 任务出现异常
Traceback (most recent call last):
File "connect.py", line 51, in create
File "connect.py", line 84, in check_area
KeyError: '2网游'
Traceback (most recent call last):
File "Tasks.py", line 131, in run
File "Tasks.py", line 23, in Daily_bag
TypeError: list indices must be integers or slices, not str
[2019-02-25 17:37:59] [Info] 开始执行每日任务
[2019-02-25 17:37:59] [Info] 签到状态:请先登录
Traceback (most recent call last):
File "OnlineHeart.py", line 120, in run
File "OnlineHeart.py", line 43, in guard_lottery
KeyError: 0
[2019-02-25 17:38:05] [Info] 心跳
[2019-02-25 17:38:06] [Error] cookie过期,将重新登录
[2019-02-25 17:38:08] [Error] 登录失败,错误信息为:账号或者密码错误
[2019-02-25 17:38:08] [Info] [2网游分区] 房间 12265 任务出现异常
Traceback (most recent call last):
File "connect.py", line 51, in create
File "connect.py", line 84, in check_area
KeyError: '2网游'
Traceback (most recent call last):
File "Tasks.py", line 131, in run
File "Tasks.py", line 23, in Daily_bag
TypeError: list indices must be integers or slices, not str
[2019-02-25 17:38:09] [Info] 开始执行每日任务
[2019-02-25 17:38:10] [Info] 签到状态:请先登录
[2019-02-25 17:38:18] [Info] [2网游分区] 房间 12265 任务出现异常
Traceback (most recent call last):
File "connect.py", line 51, in create
File "connect.py", line 84, in check_area
KeyError: '2网游'
Traceback (most recent call last):
File "OnlineHeart.py", line 120, in run
File "OnlineHeart.py", line 43, in guard_lottery
KeyError: 0
[2019-02-25 17:38:19] [Info] 心跳
Traceback (most recent call last):
File "Tasks.py", line 131, in run
File "Tasks.py", line 23, in Daily_bag
TypeError: list indices must be integers or slices, not str
[2019-02-25 17:38:20] [Info] 开始执行每日任务
[2019-02-25 17:38:20] [Error] cookie过期,将重新登录
[2019-02-25 17:38:22] [Error] 登录失败,错误信息为:账号或者密码错误
[2019-02-25 17:38:23] [Info] 签到状态:请先登录
[2019-02-25 17:38:28] [Info] [2网游分区] 房间 12265 任务出现异常
Traceback (most recent call last):
File "connect.py", line 51, in create
File "connect.py", line 84, in check_area
KeyError: '2网游'

在 2019-02-25 16:17:18，"yjqiang" <notifications@github.com> 写道：


整个的错误就是“账号或者密码错误”，导致后面的功能都因未登录而无法执行。你把账号密码里显然没问题的字符比如a-z0-9随意替换，剩下的发出来看看吧。

b站会允许\这种东西么。。。应该不会吧

**Comment by SANSHUISHUI** [comment]
今天早上开的这个跟以前显示的不一样，以前没有过主机软件阻止连接 这是第一次

**Comment by yjqiang** [comment]
> 今天早上开的这个跟以前显示的不一样，以前没有过主机软件阻止连接 这是第一次

你先把账号密码给曙光  让他看看是不是密码问题，挨个儿排除。

**Comment by SANSHUISHUI** [comment]
> 今天早上开的这个跟以前显示的不一样，以前没有过主机软件阻止连接 这是第一次
> 
> 你先把账号密码给曙光  让他看看是不是密码问题，挨个儿排除。

请问曙光是谁👀 yawwwwwn吗

**Comment by yjqiang** [comment]
> > 今天早上开的这个跟以前显示的不一样，以前没有过主机软件阻止连接 这是第一次
> > 
> > 你先把账号密码给曙光  让他看看是不是密码问题，挨个儿排除。
> 
> 请问曙光是谁👀 yawwwwwn吗
> 

@Dawnnnnnn

**Comment by SANSHUISHUI** [comment]
好的我发到他qq邮箱了

**Comment by Dawnnnnnn** [comment]
@SANSHUISHUI 你发了我一个八位数的账户，那肯定不对，目前b站只有手机号登录和邮箱登录吧

**Comment by SANSHUISHUI** [comment]
我换了台电脑之后，就可以运行了 估计是电脑问题 麻烦了 谢谢你们：）

**Comment by yjqiang** [comment]
> 我换了台电脑之后，就可以运行了 估计是电脑问题 麻烦了 谢谢你们：）

这真是个完美的反馈问题的反例…… @Dawnnnnnn

**Comment by yawwwwwn** [comment]
= =这样也行？
还有你日志里其他的问题都是网络不好啊

**Comment by SANSHUISHUI** [comment]
> = =这样也行？
> 还有你日志里其他的问题都是网络不好啊
> 额、好像你下的不是最新版？没有单机分区而且报的错我行数都对不上

我也不知道为啥会网络不好233
我下的是12月份那个，应该是最新版？

**Comment by yawwwwwn** [comment]
> 我也不知道为啥会网络不好233
> 我下的是12月份那个，应该是最新版？

不是。。。12月份那个release不是最新的。之后又更新了单机游戏分区，曙光没有同步打包。最好自己下代码跑，实在不行自己用pyInstaller打包。

**Comment by SANSHUISHUI** [comment]
> 我也不知道为啥会网络不好233
> 我下的是12月份那个，应该是最新版？
> 
> 不是。。。12月份那个release不是最新的。之后又更新了单机游戏分区，曙光没有同步打包。最好自己下代码跑，实在不行自己用pyInstaller打包。

啊好的 谢谢
