### ISSUE TITLE
你好我想问一下这个报错是什么问题？exe也是同样报错。

### ISSUE THREAD

**Issue by LHWsleeve** [Dawnnnnnn/bilibili-live-tools#201]
Task exception was never retrieved
future: <Task finished coro=<login.login_new() done, defined at /home/sleeve/文档/bilibili-live-tools-4.1/login.py:83> exception=KeyError('message',)>
**Traceback (most recent call last):
  File "/home/sleeve/文档/bilibili-live-tools-4.1/login.py", line 61, in login
    access_key = response.json()['data']['token_info']['access_token']
KeyError: 'token_info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sleeve/文档/bilibili-live-tools-4.1/login.py", line 88, in login_new
    return self.login()
  File "/home/sleeve/文档/bilibili-live-tools-4.1/login.py", line 81, in login
    Printer().printer(f"登录失败,错误信息为:{response.json()['message']}","Error","red")
KeyError: 'message'**
[2019-06-04 10:13:24] [Info]    心跳                  
[2019-06-04 10:13:24] [Info]    开始执行每日任务            
[2019-06-04 10:13:24] [Info]    检查宝箱状态              
[2019-06-04 10:13:24] [Info]    签到状态:请先登录           
[2019-06-04 10:13:25] [Info]    [5电台分区] 连接 21296161 弹幕服务器成功
[2019-06-04 10:13:25] [Info]    [7哔考分区] 连接 58467 弹幕服务器成功
[2019-06-04 10:13:25] [Info]    [6单机分区] 连接 2744359 弹幕服务器成功
[2019-06-04 10:13:25] [Info]    [2网游分区] 连接 2910685 弹幕服务器成功
[2019-06-04 10:13:25] [Info]    [1娱乐分区] 连接 10776268 弹幕服务器成功
[2019-06-04 10:13:25] [Info]    [4绘画分区] 连接 608658 弹幕服务器成功
[2019-06-04 10:13:25] [Info]    [3手游分区] 连接 3293964 弹幕服务器成功
[2019-06-04 10:13:28] [Warning] 出现一个未知msg @[2网游分区]2910685 {'cmd': 'DANMU_MSG:4:0:2:2:2:0', 'info': [[0, 1, 25, 16777215, 1559614407, 1559608206, 0, 'd5795245', 0, 0, 0], '第一次有一个使命任务，给八个黑瞳石', [389760260, '观棋不语笑忘天', 0, 0, 0, 10000, 1, ''], [2, 'Mr小兔', '兔蕾斯宝宝', 12017933, 6406234, ''], [9, 0, 9868950, '>50000'], ['', ''], 0, 0, None, {'ts': 1559614407, 'ct': '44F2AFE2'}]}
[2019-06-04 10:13:30] [Warning] 出现一个未知msg @[2网游分区]2910685 {'cmd': 'DANMU_MSG:4:0:2:2:2:0', 'info': [[0, 1, 25, 14893055, 1559614409, 462170603, 0, 'cfa3b01f', 0, 0, 0], '水个视频吧', [10712597, '梦璃Frostbite', 0, 0, 0, 10000, 1, ''], [7, 'GGBond', '猪猪侠神之手', 2910685, 5805790, ''], [12, 0, 6406234, '>50000'], ['title-179-1', 'title-179-1'], 0, 3, None, {'ts': 1559614409, 'ct': '173362E3'}]}
[2019-06-04 10:13:34] [Error]   Traceback (most recent call last):
  File "/home/sleeve/文档/bilibili-live-tools-4.1/Tasks.py", line 131, in run
    await self.Daily_bag()
  File "/home/sleeve/文档/bilibili-live-tools-4.1/Tasks.py", line 23, in Daily_bag
    for i in range(0, len(json_response['data']['bag_list'])):
TypeError: object of type 'NoneType' has no len()

[2019-06-04 10:13:34] [Info]    开始执行每日任务            
[2019-06-04 10:13:34] [Info]    签到状态:请先登录           
[2019-06-04 10:13:34] [Error]   Traceback (most recent call last):
  File "/home/sleeve/文档/bilibili-live-tools-4.1/OnlineHeart.py", line 120, in run
    await self.guard_lottery()
  File "/home/sleeve/文档/bilibili-live-tools-4.1/OnlineHeart.py", line 43, in guard_lottery
    if json_response[i]['Status']:
KeyError: 0

[2019-06-04 10:13:34] [Info]    心跳

**Comment by yawwwwwn** [comment]
在项目[首页](https://github.com/Dawnnnnnn/bilibili-live-tools)下载最新的 commit，release 里这个 4.1 的版本不是最新的，之后修过 bug，在登录这一块。
然后你再看其他的问题解决没。

**Comment by LHWsleeve** [comment]
> 在项目[首页](https://github.com/Dawnnnnnn/bilibili-live-tools)下载最新的 commit，release 里这个 4.1 的版本不是最新的，之后修过 bug，在登录这一块。
> 然后你再看其他的问题解决没。
....搞定了，不是代码的问题。
我在出错的地方debug，查找缺值....点击request发送的登录链接，进去之后发现居然手机验证页面MMP。
想起来B站一直让我改密码我没改，每次重新登录都要发验证码...
程序会误判登陆成功。手动【doge】

**Comment by yjqiang** [comment]
@yawwwwwn 为啥reopen了？这个没问题了吧

**Comment by yawwwwwn** [comment]
程序会误判登陆成功还叫不是代码的问题吗？我哭给你看嘞。你出现这种情况时的登录返回 json，你还有存吗？发出来我处理下。而且看你的报错信息，这个 json 里连 "message" 都没有，改成输出完整的 json 好了。

**Comment by yjqiang** [comment]
。。。。。

**Comment by yjqiang** [comment]
我等你搞定，这个东西是一个手机验证码的问题，而且如果你堵塞了，登陆不成功；非堵塞，你没法自己登陆。。。

**Comment by LHWsleeve** [comment]
> 程序会误判登陆成功还叫不是代码的问题吗？我哭给你看嘞。你出现这种情况时的登录返回 json，你还有存吗？发出来我处理下。而且看你的报错信息，这个 json 里连 "message" 都没有，改成输出完整的 json 好了。
-------------------------------------------------------------------------
json是没嘞。验证码导致登录不上的时候会 报出“签到状态：请先登录”的，但是倒可以领宝箱....出这个问题的时候在当前IP登录一下B站，改个密码也算能用

**Comment by yawwwwwn** [comment]
？？？可以领宝箱还行？主要是要返回的 code，不记得就算了。现在项目里的验证码打码服务器不能用了，所以尽量把账号弄正常再用吧。

**Comment by Love4Taylor** [comment]
最新 commit 类似错误, 登录状态无问题.

```
[2019-08-02 15:47:29] [Info]    心跳
[2019-08-02 15:47:35] [Warning] 出现一个未知msg @[2网游分区]2412751 {'cmd': 'WEEK_STAR_CLOCK', 'data': {'id': 199, 'expire_hour': 24, 'activity_title': '周星', 'title': '周星', 'title_text': '', 'rank': '13', 'color': '', 'cover': 'http://i0.hdslb.com/bfs/live/c81f9ec0e09bc6d5dffa4f8f583971540f36541f.png', 'extra': '', 'jump_url': 'https://live.bilibili.com/p/html/live-app-weekstar/index.html?is_live_half_webview=1&hybrid_biz=live-app-weekStar&hybrid_rotate_d=1&hybrid_half_ui=1,3,100p,70p,300e51,0,30,100;2,2,375,100p,300e51,0,30,100;3,3,100p,70p,300e51,0,30,100;4,2,375,100p,300e51,0,30,100;5,3,100p,70p,300e51,0,30,100;6,3,100p,70p,300e51,0,30,100;7,3,100p,70p,300e51,0,30,100&room_id=2412751&tab=task', 'is_close': 1, 'weight': 90, 'type': 1, 'week_text_color': '#ffffff', 'week_rank_color': '#ffffff', 'week_gift_color': '#ffffff', 'gift_img': 'https://s1.hdslb.com/bfs/vc/2faaab3dedcd8c8e4dea5ec23d0359ebf6411083.png', 'rank_name': '礼花', 'is_clock_in_over': 1, 'gift_progress': [{'id': 7, 'gift_id': 30046, 'name': '打榜', 'pic': 'http://i0.hdslb.com/bfs/live/5668f46bf2a0c57f943b925bdf4f2102a8464067.png', 'num': 50, 'current': 3}, {'id': 9, 'gift_id': 30064, 'name': '礼花', 'pic': 'http://i0.hdslb.com/bfs/live/084ff1eaa7832c4c1040772a5fec4911930bd107.png', 'num': 1, 'current': 1}, {'id': 13, 'gift_id': 30088, 'name': '奈斯', 'pic': 'http://i0.hdslb.com/bfs/live/a5b0cbc5cb995da67614bfdcfa5260756d7b5eae.png', 'num': 30, 'current': 30}]}, 'web_data': {'cover': 'https://s1.hdslb.com/bfs/vc/3e248fca6d54135a40a29c831410a745e8e8f14a.png', 'url': 'https://live.bilibili.com/p/html/live-web-weekstar/?roomid=2412751&tab=task', 'rank': '13', 'rank_name': '礼花', 'gift_img': 'https://s1.hdslb.com/bfs/vc/2faaab3dedcd8c8e4dea5ec23d0359ebf6411083.png', 'week_gift_color': '#ffffff', 'week_rank_color': '#ffffff', 'is_clock_in_over': 1, 'gift_progress': {'pic': 'http://i0.hdslb.com/bfs/live/5668f46bf2a0c57f943b925bdf4f2102a8464067.png', 'current': 3, 'num': 50}}}
[2019-08-02 15:47:40] [Error]   Traceback (most recent call last):
  File "/home/love4taylor/scripts/bilibili-live-tools/OnlineHeart.py", line 120, in run
    await self.guard_lottery()
  File "/home/love4taylor/scripts/bilibili-live-tools/OnlineHeart.py", line 43, in guard_lottery
    if json_response[i]['Status']:
KeyError: 'Status'

[2019-08-02 15:47:40] [Info]    心跳
[2019-08-02 15:47:54] [Error]   Traceback (most recent call last):
  File "/home/love4taylor/scripts/bilibili-live-tools/OnlineHeart.py", line 120, in run
    await self.guard_lottery()
  File "/home/love4taylor/scripts/bilibili-live-tools/OnlineHeart.py", line 43, in guard_lottery
    if json_response[i]['Status']:
KeyError: 'Status'
```

**Comment by yawwwwwn** [comment]
@Love4Taylor 感谢反馈，是舰长服务器那边给的数据调整了格式。今天会更新。
Ps. 下次遇到不一样的问题请新开issue。

**Comment by yawwwwwn** [comment]
> 最新 commit 类似错误, 登录状态无问题.
> 
> ```
> [2019-08-02 15:47:40] [Info]    心跳
> [2019-08-02 15:47:54] [Error]   Traceback (most recent call last):
>   File "/home/love4taylor/scripts/bilibili-live-tools/OnlineHeart.py", line 120, in run
>     await self.guard_lottery()
>   File "/home/love4taylor/scripts/bilibili-live-tools/OnlineHeart.py", line 43, in guard_lottery
>     if json_response[i]['Status']:
> KeyError: 'Status'
> ```

已修复 #208

**Comment by masterpiggg** [comment]
谢谢哈欠大佬！（洒花）
下载了新的打包档，运行很顺利，电脑白痴表示感恩！*^^*

**Comment by Alkitor** [comment]
您好，提一个bug ：执行“心跳”的时候偶尔会出现脚本直接死掉

**Comment by yawwwwwn** [comment]
> 您好，提一个bug ：执行“心跳”的时候偶尔会出现脚本直接死掉

请问“直接死掉”的意思是卡住了再没有新的输出还是脚本窗口直接弹掉。
如果是前者建议试试输入 help 等操作看看 console 有没有死掉，这种卡死我们也不知道为什么，需要提供更多信息。
如果是后者建议从 cmd 输入 run.py 运行，将在错误时能看到错误信息。

**Comment by Alkitor** [comment]
> > 您好，提一个bug ：执行“心跳”的时候偶尔会出现脚本直接死掉
> 
> 请问“直接死掉”的意思是卡住了再没有新的输出还是脚本窗口直接弹掉。
> 如果是前者建议试试输入 help 等操作看看 console 有没有死掉，这种卡死我们也不知道为什么，需要提供更多信息。
> 如果是后者建议从 cmd 输入 run.py 运行，将在错误时能看到错误信息。

抱歉没有描述清楚，是前者，打印“心跳”之后再没有输出。看来不是我一个人出现这个问题啊。我先前不知道有help这种用法，等再复现的时候我试试看（今天挂了一天都没出现），届时再提供详细信息。**不过可以提供一点线索，就是每次卡住都在打印“心跳”之后。**

**Comment by Alkitor** [comment]
> 
> 
> > 您好，提一个bug ：执行“心跳”的时候偶尔会出现脚本直接死掉
> 
> 请问“直接死掉”的意思是卡住了再没有新的输出还是脚本窗口直接弹掉。
> 如果是前者建议试试输入 help 等操作看看 console 有没有死掉，这种卡死我们也不知道为什么，需要提供更多信息。
> 如果是后者建议从 cmd 输入 run.py 运行，将在错误时能看到错误信息。

![无标题](https://user-images.githubusercontent.com/30173062/63095982-2c924700-bf9f-11e9-8920-b2ebd8105d1c.png)
help有反应，但是应该是需要联网的操作执行不了

**Comment by pjy612** [comment]
感觉应该是那个老问题。。。Scoket 意外关闭啥的，然后异常虽然捕获了。
没爆出来。。。但是因为 还有Console在后台跑。。。
程序没终止 但是 主Task已经挂掉了。。。
yj大佬之前说是 py 底层的问题。。。

**Comment by yjqiang** [comment]
@pjy612 我有说过么……应该不是底层问题 就是异常没有被捕获 卡死了

**Comment by pjy612** [comment]
@yjqiang  之前不是有个 偶尔抽风的 winerror 10038 吗？
不过 他这个 异常应该是 被捕获掉了吧？然后死在那儿了。
不然会打印出来的吧？

**Comment by yjqiang** [comment]
> @yjqiang  之前不是有个 偶尔抽风的 winerror 10038 吗？
> 不过 他这个 异常应该是 被捕获掉了吧？然后死在那儿了。
> 不然会打印出来的吧？

那个会打印

**Comment by yawwwwwn** [comment]
@Alkitor 根据大佬们的建议，可能是某个协程异常退出，但程序又没结束。你在 run.py 里的开启事件循环的地方改成`loop.run_until_complete(asyncio.wait(tasks, return_when=asyncio.FIRST_EXCEPTION))`看看报错。

**Comment by AnQin1998** [comment]
> ？？？可以领宝箱还行？主要是要返回的 code，不记得就算了。现在项目里的验证码打码服务器不能用了，所以尽量把账号弄正常再用吧。

我也出现了这个问题，返回的code是-401
之后我下载了最新的那个，在输入账号和密码之后出现了error，验证码识别服务器连接失败
然后会弹出一个图片，是验证码的图片，但是没有可以输入的地方，直接在error提示的下方输入验证码上的字母也没有用，只会提示命令无法识别。

**Comment by yawwwwwn** [comment]
> @Alkitor 根据大佬们的建议，可能是某个协程异常退出，但程序又没结束。你在 run.py 里的开启事件循环的地方改成`loop.run_until_complete(asyncio.wait(tasks, return_when=asyncio.FIRST_EXCEPTION))`看看报错。

已更新


> > ？？？可以领宝箱还行？主要是要返回的 code，不记得就算了。现在项目里的验证码打码服务器不能用了，所以尽量把账号弄正常再用吧。
> 
> 我也出现了这个问题，返回的code是-401
> 之后我下载了最新的那个，在输入账号和密码之后出现了error，验证码识别服务器连接失败
> 然后会弹出一个图片，是验证码的图片，但是没有可以输入的地方，直接在error提示的下方输入验证码上的字母也没有用，只会提示命令无法识别。

之前疏忽了，没有将输入验证码提到 console 线程之前，最新的 commit 已经改了。
另外 `"code":-401` 的消息如果方便的话希望发一下。


> ....搞定了，不是代码的问题。
> 我在出错的地方debug，查找缺值....点击request发送的登录链接，进去之后发现居然手机验证页面MMP。
> 想起来B站一直让我改密码我没改，每次重新登录都要发验证码...
> 程序会误判登陆成功。手动【doge】

手机验证的问题找到了，返回是 `{'ts': 1562810948, 'code': 0, 'data': {'status': 1, 'url': 'https://passport.bilibili.com/mobile/verifytel_h5.html?mid=405****65&tel=155****9061&source=2&keepTime=0&appId=878&subId=0&ticket=1'}}` 。遇到这种自行改密码解决。


> ？？？可以领宝箱还行？主要是要返回的 code，不记得就算了。现在项目里的验证码打码服务器不能用了，所以尽量把账号弄正常再用吧。

因为领宝箱是用的 App 的 access_token 可能在 cookies 失效后短时间内还有效。所以会出现这种情况。

**综上，该 issue 可以关了。东西太多太复杂了。遇到类似问题也请重开 issue。**
