### ISSUE TITLE
出现错误Traceback (most recent call last):

### ISSUE THREAD

**Issue by Summmm** [Dawnnnnnn/bilibili-live-tools#207]
[2019-08-02 18:48:11] [Error]   Traceback (most recent call last):
  File "C:\Users\Sleaf\Desktop\bilibili-live-tools-master\OnlineHeart.py", line 120, in run
    await self.guard_lottery()
  File "C:\Users\Sleaf\Desktop\bilibili-live-tools-master\OnlineHeart.py", line 43, in guard_lottery
    if json_response[i]['Status']:
KeyError: 'Status'

[2019-08-02 18:48:11] [Info]    心跳
[2019-08-02 18:48:21] [Error]   Traceback (most recent call last):
  File "C:\Users\Sleaf\Desktop\bilibili-live-tools-master\OnlineHeart.py", line 120, in run
    await self.guard_lottery()
  File "C:\Users\Sleaf\Desktop\bilibili-live-tools-master\OnlineHeart.py", line 43, in guard_lottery
    if json_response[i]['Status']:
KeyError: 'Status'

[2019-08-02 18:48:21] [Info]    心跳

**Comment by yawwwwwn** [comment]
已修复 #208
