### ISSUE TITLE
pyinstaller -F run.py出现问题

### ISSUE THREAD

**Issue by 1552980358** [Dawnnnnnn/bilibili-live-tools#243]
以下为输出
```
F:\bilibili-live-tools>pyinstaller -F run.py

90 INFO: PyInstaller: 3.5

91 INFO: Python: 3.8.0

92 INFO: Platform: Windows-10-10.0.18362-SP0

94 INFO: wrote F:\bilibili-live-tools\run.spec

96 INFO: UPX is not available.

98 INFO: Extending PYTHONPATH with paths

['F:\\bilibili-live-tools', 'F:\\bilibili-live-tools']

98 INFO: checking Analysis

132 INFO: checking PYZ

132 INFO: Building PYZ because PYZ-00.toc is non existent

133 INFO: Building PYZ (ZlibArchive) F:\bilibili-live-tools\build\run\PYZ-00.pyz

Traceback (most recent call last):

  File "f:\program files\python\lib\runpy.py", line 192, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "f:\program files\python\lib\runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "F:\Program Files\Python\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>

  File "f:\program files\python\lib\site-packages\PyInstaller\__main__.py", line 111, in run

    run_build(pyi_config, spec_file, **vars(args))

  File "f:\program files\python\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build

    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)

  File "f:\program files\python\lib\site-packages\PyInstaller\building\build_main.py", line 844, in main

    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))

  File "f:\program files\python\lib\site-packages\PyInstaller\building\build_main.py", line 791, in build

    exec(code, spec_namespace)

  File "F:\bilibili-live-tools\run.spec", line 18, in <module>

    pyz = PYZ(a.pure, a.zipped_data,

  File "f:\program files\python\lib\site-packages\PyInstaller\building\api.py", line 98, in __init__

    self.__postinit__()

  File "f:\program files\python\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()

  File "f:\program files\python\lib\site-packages\PyInstaller\building\api.py", line 128, in assemble

    self.code_dict = {

  File "f:\program files\python\lib\site-packages\PyInstaller\building\api.py", line 129, in <dictcomp>

    key: strip_paths_in_code(code)

  File "f:\program files\python\lib\site-packages\PyInstaller\building\utils.py", line 652, in strip_paths_in_code

    consts = tuple(

  File "f:\program files\python\lib\site-packages\PyInstaller\building\utils.py", line 653, in <genexpr>
    strip_paths_in_code(const_co, new_filename)

  File "f:\program files\python\lib\site-packages\PyInstaller\building\utils.py", line 660, in strip_paths_in_code

    return code_func(co.co_argcount, co.co_kwonlyargcount, co.co_nlocals, co.co_stacksize,

TypeError: an integer is required (got type bytes)
```

**Comment by Dawnnnnnn** [comment]
换个Python版本试试？感觉要去pyinstaller项目问了
