### ISSUE TITLE
这是什么问题鸭

### ISSUE THREAD

**Issue by henut** [Dawnnnnnn/bilibili-live-tools#250]
[2019-12-05 22:55:59] [Info]    心跳
[2019-12-05 22:56:11] [Error]   Traceback (most recent call last):
  File "C:\Users\Lenovo\Downloads\bilibili-live-tools-master\OnlineHeart.py", line 133, in run
    await self.guard_lottery()
  File "C:\Users\Lenovo\Downloads\bilibili-live-tools-master\OnlineHeart.py", line 45, in guard_lottery
    GuardId = json_response[i]['GuardId']
KeyError: 'GuardId'

**Comment by Billyzou0741326** [comment]
看了下https://github.com/Dawnnnnnn/bilibili-live-tools/blob/d3bc6cb16620e727dfbf031f9f40adb3fac11803/OnlineHeart.py#L45
应该是服务器端的返回值异常... 

Dawn大佬有活干了2333

**Comment by yawwwwwn** [comment]
这个是因为服务器返回数据改了，见 [#0d5905b](https://github.com/Dawnnnnnn/bilibili-live-tools/commit/0d5905ba5b75b9e3bbb13ec5a8d40ef0f1af2fe9)。

**Comment by Billyzou0741326** [comment]
没注意到是旧commit的版本2333
