### ISSUE TITLE
docker版报错

### ISSUE THREAD

**Issue by JIA-Jimmy** [Dawnnnnnn/bilibili-live-tools#253]
系统是debian9，python版本3.6.4，运行以后无效，查看log发现报错

[2019-12-18 06:37:43] [Info]    [3手游分区] 连接 21387272 弹幕服务器成功
[2019-12-18 06:37:45] [Error]   Traceback (most recent call last):
  File "/app/pkLottery.py", line 64, in run
    await self.pk_lottery()
  File "/app/pkLottery.py", line 26, in pk_lottery
    PKId = json_response[i]['Id']
KeyError: 0

[2019-12-18 06:37:48] [Error]   Traceback (most recent call last):
  File "/app/Tasks.py", line 132, in run
    await self.Daily_bag()
  File "/app/Tasks.py", line 23, in Daily_bag
    for i in range(0, len(json_response['data']['bag_list'])):
TypeError: object of type 'NoneType' has no len()

[2019-12-18 06:37:48] [Info]    开始执行每日任务            
[2019-12-18 06:37:48] [Error]   Traceback (most recent call last):
  File "/app/OnlineHeart.py", line 134, in run
    await self.guard_lottery()
  File "/app/OnlineHeart.py", line 45, in guard_lottery
    GuardId = json_response[i]['Id']
KeyError: 0

**Comment by JIA-Jimmy** [comment]
对不起，原来是我把账号填错了

**Comment by Billyzou0741326** [comment]
没事hhh解决了就好
