### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by lyf1134** [Dawnnnnnn/bilibili-live-tools#263]
[2020-02-21 19:39:14] [Info]    发现监控缺失 [7]
[2020-02-21 19:39:14] [Error]   Traceback (most recent call last):
  File "C:\Users\\Desktop\bilibili-live-tools-master\Dawnnnnnn\statistics.py", line 110, in clean_TV
    await utils.check_area_list(to_check)
  File "C:\Users\\Desktop\bilibili-live-tools-master\Dawnnnnnn\utils.py", line 259, in check_area_list
    await connect().check_area(area_id, **kwargs)
  File "C:\Users\\Desktop\bilibili-live-tools-master\Dawnnnnnn\connect.py", line 82, in check_area
    area = [tem_area for tem_area in connect.areas if str(area) in tem_area][0]
IndexError: list index out of range

**Comment by lyf1134** [comment]
[2020-02-21 19:34:14] [Info]    [2网游分区] 房间 79558 直播状态正常
[2020-02-21 19:34:15] [Info]    [3手游分区] 房间 14411852 直播状态正常
[2020-02-21 19:34:15] [Info]    [6单机分区] 房间 9884872 直播状态正常
[2020-02-21 19:34:15] [Info]    [1娱乐分区] 房间 5169315 直播状态正常
[2020-02-21 19:34:16] [Info]    [5电台分区] 房间 21441066 直播状态正常
[2020-02-21 19:34:16] [Info]    [4绘画分区] 房间 4149257 直播状态正常
[2020-02-21 19:34:16] [Info]    [8战疫分区] 房间 21818495 直播状态正常

今天好像分区换了

**Comment by yawwwwwn** [comment]
已更新 [#69a596c](https://github.com/Dawnnnnnn/bilibili-live-tools/commit/69a596c4e402671585afcb4fa948c1b300b3115c)。
（<u>我不得不吐槽一下B站这个战疫分区就三个官方直播间。要不是我之前的设计确实有问题我都想直接鸽到战疫结束。</u>）
