### ISSUE TITLE
更新commit后出现监控缺失 7错误

### ISSUE THREAD

**Issue by SenaKawasumi** [Dawnnnnnn/bilibili-live-tools#266]
更新到最新的commit 出现监控缺失7的错误
> [2020-02-25 11:13:05] [Info]    发现监控缺失 7
[2020-02-25 11:13:05] [Error]   Traceback (most recent call last):
  File "E:\bilibili-live-tools\statistics.py", line 113, in clean_TV
    await utils.check_area_list(to_check)
  File "E:\bilibili-live-tools\utils.py", line 259, in check_area_list
    for area_id in area_list:
TypeError: 'int' object is not iterable

更新之前似乎没出现过...？

**Comment by yawwwwwn** [comment]
我人晕了，昨天的 commit 就是为了修复这个分区缺失误报的，还是不对吗。我今晚再看看。

**Comment by yawwwwwn** [comment]
已修复 [#66db5ca](https://github.com/Dawnnnnnn/bilibili-live-tools/commit/66db5ca5d61bcf8bf5aa47da616277d8a7ddf4a7)。
