### ISSUE TITLE
最近日志中经常出现的错误 IndexError: list index out of range

### ISSUE THREAD

**Issue by zazaluMonster** [Dawnnnnnn/bilibili-live-tools#277]
```
[2020-03-04 22:24:12] [Error]   Traceback (most recent call last):
  File "/root/third-app/bilibili-live-tools-master/statistics.py", line 110, in clean_TV
    await utils.check_area_list(to_check)
  File "/root/third-app/bilibili-live-tools-master/utils.py", line 259, in check_area_list
    await connect().check_area(area_id, **kwargs)
  File "/root/third-app/bilibili-live-tools-master/connect.py", line 82, in check_area
    area = [tem_area for tem_area in connect.areas if str(area) in tem_area][0]
IndexError: list index out of range
```

**Comment by zazaluMonster** [comment]
```
[2020-03-04 22:24:12] [Info]    发现监控缺失 [7]
[2020-03-04 22:24:12] [Error]   Traceback (most recent call last):
  File "/root/third-app/bilibili-live-tools-master/statistics.py", line 110, in clean_TV
    await utils.check_area_list(to_check)
  File "/root/third-app/bilibili-live-tools-master/utils.py", line 259, in check_area_list
    await connect().check_area(area_id, **kwargs)
  File "/root/third-app/bilibili-live-tools-master/connect.py", line 82, in check_area
    area = [tem_area for tem_area in connect.areas if str(area) in tem_area][0]
IndexError: list index out of range
```

**Comment by zazaluMonster** [comment]
有和我一样情况的同学吗？

**Comment by zazaluMonster** [comment]
我更新下代码吧。 看了下提交记录有不少修复bug。

**Comment by Billyzou0741326** [comment]
7想必是战役分区了 之前有次更新确实解决了这个
