### ISSUE TITLE
这啥

### ISSUE THREAD

**Issue by 13frost** [Dawnnnnnn/bilibili-live-tools#291]
[2020-04-22 21:20:20] [Info]    心跳
[2020-04-22 21:20:23] [Error]   Traceback (most recent call last):
  File "Tasks.py", line 131, in run
  File "Tasks.py", line 34, in DoSign
KeyError: 'msg'

[2020-04-22 21:20:23] [Info]    开始执行每日任务
[2020-04-22 21:20:27] [Error]   Traceback (most recent call last):
  File "pkLottery.py", line 64, in run
  File "pkLottery.py", line 26, in pk_lottery
KeyError: 0

[2020-04-22 21:20:32] [Error]   Traceback (most recent call last):
  File "OnlineHeart.py", line 133, in run
  File "OnlineHeart.py", line 45, in guard_lottery
KeyError: 0

**Comment by shoucandanghehe** [comment]
B站改返回值了吧

**Comment by yawwwwwn** [comment]
你使用的是至少五个月前的版本，请检查一下，谢谢。
