### ISSUE TITLE
Failed when parsing

### ISSUE THREAD

**Issue by Franinc** [Dawnnnnnn/bilibili-live-tools#303]
搜了搜历史issues没结果，提交下新bug？凌晨记录完这一串后程序不工作了。
```
[2020-05-09 00:00:40] [Lottery] 获取到房间 7685374 编号 2467377 的上船奖励: 粉丝勋章亲密度+1（当前佩戴）
[2020-05-09 00:00:40] [Lottery] 获取到房间 21447491 编号 2467373 的上船奖励: 粉丝勋章亲密度+1（当前佩戴）
[2020-05-09 00:00:40] [Error]   Failed when parsing: {"cmd": "Guard", "code": 0, "msg": "", "data": {"Id": 2467285, "RoomId": 5918387, "MasterName": "\u5357\u6e9f\u541b", "MasterId": 7360754, "Sender": "Mos_pomoka", "SenderId": 398947280
Traceback (most recent call last):
  File "/home/seu1/bilibili-live-tools/TCP_monitor.py", line 119, in ReadSocketData
    json_data = json.loads(body)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 185 (char 184)

[2020-05-09 00:00:40] [Error]   Failed when parsing: ime": 1588953608, "EndTime": 1588954808, "Type": 3}}  {"cmd": "Guard", "code": 0, "msg": "", "data": {"Id": 2467406, "RoomId": 4464464, "MasterName": "\u6267\u4e0e\u541b", "MasterId": 39764046, "Sender": "\u5f53\u98ce\u8fc7\u5883w", "SenderId": 10968126, "Time": 1588953609, "EndTime": 1588954809, "Type": 3}}  {"cmd": "Guard", "code": 0, "msg": "", "data": {"Id": 2467343, "RoomId": 21939662, "MasterName": "\u5fa1\u9f99\u5927\u4fa0", "MasterId": 514973662, "Sender": "\u5e72\u7269\u59b9\u5c0f\u57cb122", "SenderId": 14360681, "Time": 1588953609, "EndTime": 1588954809, "Type": 3}}  {"cmd": "Guard", "code": 0, "msg": "", "data": {"Id": 2467322, "RoomId": 785054, "MasterName": "\u67aa\u6cd5\u5f88\u9a6c\u7684\u8001\u9ed1", "MasterId": 27337724, "Sender": "\u60c5\u6df1\u5230\u6765\u751f", "SenderId": 13268359, "Time": 1588953604, "EndTime": 1588954804, "Type": 3}}   {"cmd": "Guard", "code": 0, "msg": "", "data": {"Id": 2467420, "RoomId": 1345068, "MasterName": "\u67ab\u9171\u9700\u8981\u6c89\u7a33\u5207\u52ff\u6025\u8e81", "MasterId": 36816307, "Sender": "\u6817\u51c9", "SenderId": 11611704, "Time": 1588953608, "EndTime": 1588954808, "Type": 3}}  {"cmd": "Guard", "code": 0, "msg": "", "data": {"Id": 2467419, "RoomId": 399477, "MasterName": "\u4e0d\u7720\u7684\u9b42\u9b42", "MasterId": 27298546, "Sender": "\u4e0d\u7720\u7684\u529b\u529b", "SenderId": 291281848, "Time": 1588953608, "EndTime": 1588954808, "Type": 3}
Traceback (most recent call last):
  File "/home/seu1/bilibili-live-tools/TCP_monitor.py", line 119, in ReadSocketData
    json_data = json.loads(body)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[2020-05-09 00:00:41] [Info]    <Task pending coro=<bilibiliClient.HeartbeatLoop() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:113> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb07d359c>()]>>
<Task pending coro=<Biliconsole.run() running at /home/seu1/bilibili-live-tools/biliconsole.py:90> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cfcd4>()]>>
<Task pending coro=<LotteryResult.query() running at /home/seu1/bilibili-live-tools/LotteryResult.py:11> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cf0d4>()]>>
<Task pending coro=<handle_1_TV_raffle() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:23> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cf6ec>()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.6/asyncio/tasks.py:380]>
<Task pending coro=<handle_1_TV_raffle() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:23> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cf284>()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.6/asyncio/tasks.py:380]>
<Task pending coro=<bilibiliClient.connectServer() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:105> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb07d3cd4>()]>>
<Task pending coro=<handle_1_room_TV() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:67> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cff5c>()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.6/asyncio/tasks.py:380]>
<Task pending coro=<Rafflehandler.run() running at /home/seu1/bilibili-live-tools/rafflehandler.py:25> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cf5e4>()]>>
<Task finished coro=<handle_1_TV_raffle() done, defined at /home/seu1/bilibili-live-tools/bilibiliCilent.py:15> result=None>
<Task pending coro=<StreamReader.read() running at /usr/lib/python3.6/asyncio/streams.py:634> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb07d374c>()]> cb=[_release_waiter(<Future pendi...xb09cf02c>()]>)() at /usr/lib/python3.6/asyncio/tasks.py:316]>
<Task pending coro=<handle_1_TV_raffle() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:23> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cf4f4>()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.6/asyncio/tasks.py:380]>
<Task pending coro=<handle_1_TV_raffle() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:23> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb07d3fa4>()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.6/asyncio/tasks.py:380]>
<Task pending coro=<PKLottery.run() running at /home/seu1/bilibili-live-tools/pkLottery.py:75> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb07d3ecc>()]>>
<Task pending coro=<Silver.run() running at /home/seu1/bilibili-live-tools/Silver.py:52> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb60c9e3c>()]>>
<Task finished coro=<handle_1_room_TV() done, defined at /home/seu1/bilibili-live-tools/bilibiliCilent.py:42> result=None>
<Task pending coro=<GuardLottery.run() running at /home/seu1/bilibili-live-tools/guardLottery.py:73> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cf554>()]>>
<Task pending coro=<handle_1_TV_raffle() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:23> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb07d3194>()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.6/asyncio/tasks.py:380]>
<Task pending coro=<OnlineHeart.run() running at /home/seu1/bilibili-live-tools/OnlineHeart.py:93> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cf254>()]>>
<Task pending coro=<bilibiliClient.connectServer() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:105> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cfaac>()]>>
<Task pending coro=<StreamReader.read() running at /usr/lib/python3.6/asyncio/streams.py:634> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cf5cc>()]> cb=[_release_waiter(<Future pendi...xb09cfbcc>()]>)() at /usr/lib/python3.6/asyncio/tasks.py:316]>
<Task pending coro=<handle_1_TV_raffle() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:23> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb07d380c>()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.6/asyncio/tasks.py:380]>
<Task finished coro=<TCP_monitor.connectServer() done, defined at /home/seu1/bilibili-live-tools/TCP_monitor.py:37> exception=UnicodeDecodeError('utf-8', b'\xff{"cmd": "Guard", "code": 0, "msg": "", "data": {"Id": 2467284, "RoomId": 49058, "MasterName": "\\u6728\\u5c71\\u8138\\u6eda\\u952e\\u76d8", "MasterId": 2627477, "Sender": "A-Adan", "SenderId": 98774642, "Time": 1588953609, "EndTime": 1588954809, "Type": 3}}\x00\x00\x01\x08{"cmd": "Guard", "code": 0, "msg": "", "data": {"Id": 2467216, "RoomId": 6052407, "MasterName": "\\u742a\\u5bf6\\u4e0d\\u54ed", "MasterId": 35203978, "Sender": "\\u96f6\\u5d0e\\u70bd\\u7fbd", "SenderId": 46213180, "Time": 1588953609, "EndTime": 1588954809, "Type": 3}}\x00\x00\x01\x0c{"cmd": "Guard", "code": 0, "msg": "", "data": {"Id": 2467283, "RoomId": 54912, "MasterName": "\\u731c\\u5341\\u516b", "MasterId": 19088449, "Sender": "\\u59b9\\u7eb8\\u5bb6\\u7684\\u9ea6\\u5b50", "SenderId": 18043614, "Time": 1588953604, "EndTime": 1588954804, "Type": 3}}\x00\x00\x00\xf3{"cmd": "Guard", "code": 0, "msg": "", "data": {"Id": 2467202, "RoomId": 5224276, "MasterName": "\\u4e88\\u7ef5\\u7ef5", "MasterId": 11449972, "Sender": "-Kuriboh-", "SenderId": 14243099, "Time": 1588953603, "EndTime": 1588954803, "Type": 3}}\x00\x00\x01\x05{"cmd": "Guard", "code": 0, "msg": "", "data": {"Id": 2467421, "RoomId": 10401, "MasterName": "Gluneko", "MasterId": 301940, "Sender": "\\u6700\\u540e\\u4e00\\u7897\\u7ea2\\u70e7\\u8089", "SenderId": 10337339, "Time": 1588953608, "EndTime": 1588954808, "Type": 3}}\x00\x00\x01\x06{"cmd": "Guard", "code": 0, "msg": "", "data": {"Id": 2467248, "RoomId": 21013446, "MasterName": "\\u96eb\\u308b\\u308b_Official", "MasterId": 387636363, "Sender": "\\u8001\\u8872\\u9171", "SenderId": 4284786, "Time": 1588953604, "EndTime": 1588954804, "Type": 3}}\x00\x00\x00\xff{"cmd": "Guard", "code": 0, "msg": "", "data": {"Id": 2467280, "RoomId": 713115, "MasterName": "\\u7edc\\u9065Haruka", "MasterId": 1846928, "Sender": "black\\u5c0f\\u5c0f\\u4e03", "SenderId": 43422267, "Time": 1588953605, "EndTime": 1588954805, "Type": 3}}\x00\x00\x01\n{"cmd": "Guard", "code": 0, "msg": "", "data": {"Id": 2467212, "RoomId": 1256354, "MasterName": "\\u5927\\u624e\\u840c\\u59b9s", "MasterId": 29132998, "Sender": "\\u677e\\u677e\\u624e\\u624e", "SenderId": 500842041, "Time": 1588953605, "EndTime": 1588954805, "Type": 3}}', 0, 1, 'invalid start byte')>
<Task pending coro=<bilibiliClient.connectServer() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:105> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cf20c>()]>>
<Task pending coro=<StreamReader.read() running at /usr/lib/python3.6/asyncio/streams.py:634> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb07d32cc>()]> cb=[_release_waiter(<Future pendi...xb07d3cd4>()]>)() at /usr/lib/python3.6/asyncio/tasks.py:316]>
<Task pending coro=<bilibiliClient.HeartbeatLoop() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:113> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb07d347c>()]>>
<Task pending coro=<handle_1_room_TV() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:67> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb07d3c74>()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.6/asyncio/tasks.py:380]>
<Task pending coro=<TCP_monitor.HeartbeatLoop() running at /home/seu1/bilibili-live-tools/TCP_monitor.py:61> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cfb54>()]>>
<Task pending coro=<bilibiliClient.HeartbeatLoop() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:113> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb07d37c4>()]>>
<Task pending coro=<handle_1_room_TV() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:67> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cf1ac>()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.6/asyncio/tasks.py:380]>
<Task pending coro=<bilibiliClient.HeartbeatLoop() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:113> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb07d350c>()]>>
<Task pending coro=<Schedule.run() running at /home/seu1/bilibili-live-tools/schedule.py:69> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb4eb380c>()]>>
<Task pending coro=<handle_1_room_TV() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:67> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cf074>()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.6/asyncio/tasks.py:380]>
<Task pending coro=<bilibiliClient.connectServer() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:105> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cf02c>()]>>
<Task pending coro=<handle_1_TV_raffle() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:23> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cf104>()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.6/asyncio/tasks.py:380]>
<Task pending coro=<StreamReader.read() running at /usr/lib/python3.6/asyncio/streams.py:634> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cfc44>()]> cb=[_release_waiter(<Future pendi...xb09cf20c>()]>)() at /usr/lib/python3.6/asyncio/tasks.py:316]>
<Task pending coro=<StreamReader.read() running at /usr/lib/python3.6/asyncio/streams.py:634> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cf0a4>()]> cb=[_release_waiter(<Future pendi...xb09cf794>()]>)() at /usr/lib/python3.6/asyncio/tasks.py:316]>
<Task pending coro=<handle_1_TV_raffle() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:23> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb07d3bfc>()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.6/asyncio/tasks.py:380]>
<Task pending coro=<handle_1_room_TV() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:67> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb07d3e9c>()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.6/asyncio/tasks.py:380]>
<Task pending coro=<handle_1_room_TV() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:67> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb07d32e4>()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.6/asyncio/tasks.py:380]>
<Task pending coro=<Tasks.run() running at /home/seu1/bilibili-live-tools/Tasks.py:140> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb6a3dca4>()]>>
<Task pending coro=<StreamReader.read() running at /usr/lib/python3.6/asyncio/streams.py:634> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cf89c>()]> cb=[_release_waiter(<Future pendi...xb09cfaac>()]>)() at /usr/lib/python3.6/asyncio/tasks.py:316]>
<Task pending coro=<handle_1_TV_raffle() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:23> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cfc2c>()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.6/asyncio/tasks.py:380]>
<Task pending coro=<bilibiliClient.connectServer() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:105> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cf794>()]>>
<Task pending coro=<handle_1_room_TV() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:67> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cf77c>()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.6/asyncio/tasks.py:380]>
<Task pending coro=<handle_1_room_TV() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:67> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cf2e4>()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.6/asyncio/tasks.py:380]>
<Task pending coro=<bilibiliClient.HeartbeatLoop() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:113> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb07d3d34>()]>>
<Task pending coro=<bilibiliClient.HeartbeatLoop() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:113> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb07d3794>()]>>
<Task pending coro=<bilibiliClient.connectServer() running at /home/seu1/bilibili-live-tools/bilibiliCilent.py:105> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cfbcc>()]>>
<Task pending coro=<connect.create() running at /home/seu1/bilibili-live-tools/connect.py:47> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb09cfefc>()]>>
[2020-05-09 00:00:41] [Info]    'PENDING'           
[2020-05-09 00:00:41] [Info]    'PENDING'           
[2020-05-09 00:00:41] [Info]    'PENDING'           
[2020-05-09 00:00:41] [Info]    'PENDING'           
[2020-05-09 00:00:41] [Info]    'PENDING'           
[2020-05-09 00:00:41] [Info]    'PENDING'           
[2020-05-09 00:00:41] [Info]    'PENDING'           
[2020-05-09 00:00:41] [Info]    'PENDING'           
[2020-05-09 00:00:41] [Info]    'PENDING'           
[2020-05-09 00:00:41] [Info]    'FINISHED'          
[2020-05-09 00:00:41] [Error]   Task err: UnicodeDecodeError('utf-8', b'\xff{"cmd": "Guard", "code": 0, "msg": "", "data": {"Id": 2467284, "RoomId": 49058, "MasterName": "\\u6728\\u5c71\\u8138\\u6eda\\u952e\\u76d8", "MasterId": 2627477, "Sender": "A-Adan", "SenderId": 98774642, "Time": 1588953609, "EndTime": 1588954809, "Type": 3}}\x00\x00\x01\x08{"cmd": "Guard", "code": 0, "msg": "", "data": {"Id": 2467216, "RoomId": 6052407, "MasterName": "\\u742a\\u5bf6\\u4e0d\\u54ed", "MasterId": 35203978, "Sender": "\\u96f6\\u5d0e\\u70bd\\u7fbd", "SenderId": 46213180, "Time": 1588953609, "EndTime": 1588954809, "Type": 3}}\x00\x00\x01\x0c{"cmd": "Guard", "code": 0, "msg": "", "data": {"Id": 2467283, "RoomId": 54912, "MasterName": "\\u731c\\u5341\\u516b", "MasterId": 19088449, "Sender": "\\u59b9\\u7eb8\\u5bb6\\u7684\\u9ea6\\u5b50", "SenderId": 18043614, "Time": 1588953604, "EndTime": 1588954804, "Type": 3}}\x00\x00\x00\xf3{"cmd": "Guard", "code": 0, "msg": "", "data": {"Id": 2467202, "RoomId": 5224276, "MasterName": "\\u4e88\\u7ef5\\u7ef5", "MasterId": 11449972, "Sender": "-Kuriboh-", "SenderId": 14243099, "Time": 1588953603, "EndTime": 1588954803, "Type": 3}}\x00\x00\x01\x05{"cmd": "Guard", "code": 0, "msg": "", "data": {"Id": 2467421, "RoomId": 10401, "MasterName": "Gluneko", "MasterId": 301940, "Sender": "\\u6700\\u540e\\u4e00\\u7897\\u7ea2\\u70e7\\u8089", "SenderId": 10337339, "Time": 1588953608, "EndTime": 1588954808, "Type": 3}}\x00\x00\x01\x06{"cmd": "Guard", "code": 0, "msg": "", "data": {"Id": 2467248, "RoomId": 21013446, "MasterName": "\\u96eb\\u308b\\u308b_Official", "MasterId": 387636363, "Sender": "\\u8001\\u8872\\u9171", "SenderId": 4284786, "Time": 1588953604, "EndTime": 1588954804, "Type": 3}}\x00\x00\x00\xff{"cmd": "Guard", "code": 0, "msg": "", "data": {"Id": 2467280, "RoomId": 713115, "MasterName": "\\u7edc\\u9065Haruka", "MasterId": 1846928, "Sender": "black\\u5c0f\\u5c0f\\u4e03", "SenderId": 43422267, "Time": 1588953605, "EndTime": 1588954805, "Type": 3}}\x00\x00\x01\n{"cmd": "Guard", "code": 0, "msg": "", "data": {"Id": 2467212, "RoomId": 1256354, "MasterName": "\\u5927\\u624e\\u840c\\u59b9s", "MasterId": 29132998, "Sender": "\\u677e\\u677e\\u624e\\u624e", "SenderId": 500842041, "Time": 1588953605, "EndTime": 1588954805, "Type": 3}}', 0, 1, 'invalid start byte')
[2020-05-09 00:00:41] [Info]    'PENDING'           
[2020-05-09 00:00:41] [Info]    'PENDING'
```

**Comment by ThreeCatsLoveFish** [comment]
我也有这个问题出现

**Comment by Hitiko** [comment]
我也有相同问题

**Comment by Dawnnnnnn** [comment]
稍微修了一下，不知道为什么发过来的数据不全，新版本加了debug信息，下次应该就能看出来问题了
