### ISSUE TITLE
 No module named 'six'

### ISSUE THREAD

**Issue by Jetkins668** [Dawnnnnnn/bilibili-live-tools#305]
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from TCP_monitor import TCP_monitor
  File "D:\QQliulanqidownload\yasuo\bilibili-live-tools-master (1)\bilibili-live-tools-master\TCP_monitor.py", line 14, in <module>
    from guardLottery import GuardLottery
  File "D:\QQliulanqidownload\yasuo\bilibili-live-tools-master (1)\bilibili-live-tools-master\guardLottery.py", line 8, in <module>
    import encrypt
  File "D:\QQliulanqidownload\yasuo\bilibili-live-tools-master (1)\bilibili-live-tools-master\encrypt.py", line 2, in <module>
    from six import int2byte
ModuleNotFoundError: No module named 'six'
我是小白，可能表达的不太对，谅解，谢谢。求大佬帮忙解决一下

**Comment by ThreeCatsLoveFish** [comment]
你python需要的package装过吗
pip install -r requirements.txt

**Comment by Dawnnnnnn** [comment]
pip install six
试试
我咋记得这是个内置库，难道不是吗。。

**Comment by Jetkins668** [comment]
上次更新我才用的这个工具，当时所需要的库我都安装了，还能运行，这次的更新的requirements里也没six库呀，我装了six库和brotli库现在能运行了，谢谢大佬们。
