### ISSUE TITLE
出现一个报错，不知应该怎样解决

### ISSUE THREAD

**Issue by GOOD-AN** [Dawnnnnnn/bilibili-live-tools#326]
[2020-07-27 12:37:44] [run:195]           [Error]   Traceback (most recent call last):
  File "C:\Users\wjt\Desktop\wenjian\1\bilibili-live-tools-master1\Tasks.py", line 181, in run
    await asyncio.wait(coroutine_list)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\asyncio\tasks.py", line 380, in wait
    raise ValueError('Set of coroutines/Futures is empty.')
ValueError: Set of coroutines/Futures is empty.

**Comment by Dawnnnnnn** [comment]
你是0勋章吗

**Comment by GOOD-AN** [comment]
对的，有一个号没有勋章

**Comment by GOOD-AN** [comment]
非常感谢！！！
