### ISSUE TITLE
看不懂的提示。。。

### ISSUE THREAD

**Issue by yjqiang** [Dawnnnnnn/bilibili-live-tools#40]
Task exception was never retrieved
future: <Task finished coro=<bilibiliClient.connectServer() done, defined at /private/var/mobile/Containers/Shared/AppGroup/6477072F-46E3-43B7-9C2B-4877AD7187C2/File Provider Storage/Repositories/bilibili-live-tools/bilibiliCilent.py:21> exception=error('unpack requires a bytes object of length 4',)>
Traceback (most recent call last):
  File "/var/containers/Bundle/Application/9F565D30-C54B-4210-902B-874D7A5AB814/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/private/var/mobile/Containers/Shared/AppGroup/6477072F-46E3-43B7-9C2B-4877AD7187C2/File Provider Storage/Repositories/bilibili-live-tools/bilibiliCilent.py", line 29, in connectServer
    await self.ReceiveMessageLoop()
  File "/private/var/mobile/Containers/Shared/AppGroup/6477072F-46E3-43B7-9C2B-4877AD7187C2/File Provider Storage/Repositories/bilibili-live-tools/bilibiliCilent.py", line 58, in ReceiveMessageLoop
    expr, = unpack('!I', tmp)
struct.error: unpack requires a bytes object of length 4

**Comment by yjqiang** [comment]
未退出
但是多次出现

**Comment by Dawnnnnnn** [comment]
弹幕服务器断线了吧，应该再过十秒就会继续尝试重连

**Comment by yjqiang** [comment]
对 好像就出在连接弹幕服务器提示后面

**Comment by yjqiang** [comment]
如果处理正确了话，就用try catch处理了吧

**Comment by Dawnnnnnn** [comment]
现在那个重连功能只是我瞎改的。。。处于勉强能用的阶段

**Comment by yjqiang** [comment]
。。。你妹 那你就先把 #27 做掉吧

**Comment by yjqiang** [comment]
read那里如果收到EFO（tcp链接断开），会返回空字节，导致后面的unpack失败。
解决方法有时间再想。

**Comment by yjqiang** [comment]
可以判断是否为空，设置self.bilibili.connected为False并break掉
等验证

**Comment by lovezm** [comment]
我又个大胆的想法 滑稽.jpg
[account]
username =
password =
[account1]
username =
password =

**Comment by yjqiang** [comment]
妈蛋 你自己新开issue去……

**Comment by yjqiang** [comment]
妈蛋 重新出现了，与断线无关

**Comment by yjqiang** [comment]
数据包切块了
