### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by ghosx** [Dawnnnnnn/bilibili-live-tools#96]
```
python3 main.py
start OK!
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from OnlineHeart import OnlineHeart
  File "/home/pi/bilibili-live-tools/OnlineHeart.py", line 16
    async def apppost_heartbeat(self):
            ^
SyntaxError: invalid syntax
```

**Comment by Dawnnnnnn** [comment]
重新下载，覆盖...好像你修改了点什么东西...

**Comment by ghosx** [comment]
我是直接clone下来运行的python3 main.py会出现格式错误，但是python3 run.py就可以正常运行

**Comment by Dawnnnnnn** [comment]
懂了，linux服务器需要修改main.py中的 python 为 python3
